// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ExternalAnnotationsGenerator")]
[assembly: AssemblyProductAttribute("ExternalAnnotationsGenerator")]
[assembly: AssemblyDescriptionAttribute("Fluent Library for generating ReSharper External annotation files")]
[assembly: AssemblyVersionAttribute("2.3")]
[assembly: AssemblyFileVersionAttribute("2.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.3";
    }
}
