// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ExternalAnnotationsGenerator")]
[assembly: AssemblyProductAttribute("ExternalAnnotationsGenerator")]
[assembly: AssemblyDescriptionAttribute("Fluent Library for generating ReSharper External annotation files")]
[assembly: AssemblyVersionAttribute("2.2")]
[assembly: AssemblyFileVersionAttribute("2.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.2";
    }
}
