// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ExternalAnnotationsGenerator")]
[assembly: AssemblyProductAttribute("ExternalAnnotationsGenerator")]
[assembly: AssemblyDescriptionAttribute("Fluent Library for generating ReSharper External annotation files")]
[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0.0";
    }
}
